import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://theabbapayroll.com/login');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('carldominiccueva@gmail.com');
  await page.getByRole('textbox', { name: 'Email Address' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('CDNC19960308.');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('CDNC19960308.nico');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: ' Employees' }).click();
  await page.getByRole('link', { name: ' Schedules' }).click();
  await page.locator('div').filter({ hasText: /^Date From$/ }).getByLabel('Calendar icon').click();
  await page.locator('[data-test-id="dp-2025-10-01"]').getByText('1').click();
  await page.locator('div').filter({ hasText: /^Date To$/ }).getByLabel('Calendar icon').click();
  await page.locator('[data-test-id="dp-2025-10-07"]').getByText('7').click();
  await page.locator('div').filter({ hasText: /^Date From$/ }).locator('[data-test-id="dp-input"]').click();
  await page.locator('[data-test-id="dp-input"]').first().fill('/2025');
  await page.locator('[data-test-id="dp-input"]').first().press('ArrowRight');
  await page.locator('[data-test-id="dp-input"]').first().press('ArrowRight');
  await page.locator('[data-test-id="dp-input"]').first().press('ArrowRight');
  await page.locator('[data-test-id="dp-input"]').first().press('ArrowRight');
  await page.locator('[data-test-id="dp-input"]').first().press('ArrowRight');
  await page.locator('[data-test-id="dp-input"]').first().fill('');
  await page.locator('div').filter({ hasText: /^Date To$/ }).locator('[data-test-id="dp-input"]').click();
  await page.locator('[data-test-id="dp-input"]').nth(1).fill('/2025');
  await page.locator('[data-test-id="dp-input"]').nth(1).press('ArrowRight');
  await page.locator('[data-test-id="dp-input"]').nth(1).press('ArrowRight');
  await page.locator('[data-test-id="dp-input"]').nth(1).press('ArrowRight');
  await page.locator('[data-test-id="dp-input"]').nth(1).press('ArrowRight');
  await page.locator('[data-test-id="dp-input"]').nth(1).press('ArrowRight');
  await page.locator('[data-test-id="dp-input"]').nth(1).press('ArrowRight');
  await page.locator('[data-test-id="dp-input"]').nth(1).fill('');
  await page.getByRole('button', { name: '' }).click();
  await page.getByRole('textbox', { name: 'Search...' }).click();
  await page.getByRole('textbox', { name: 'Search...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search...' }).fill('A');
  await page.getByRole('textbox', { name: 'Search...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search...' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Search...' }).press('Enter');
  await page.getByRole('button', { name: '' }).click();
  await page.getByRole('combobox').filter({ hasText: 'ALLWeeklyQuincenalMonthlyNothing matched your searchNo available options' }).locator('div').nth(1).click();
  await page.getByRole('option', { name: 'Quincenal Press enter to' }).locator('span').first();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('button', { name: '' }).click();
  await page.getByRole('button', { name: 'Reset' }).click();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('combobox').locator('div').first().click();
  await page.getByRole('option', { name: '5', exact: true }).locator('span').first().click();
  await page.getByRole('link', { name: ' Next' }).click();
  await page.getByRole('link', { name: ' Previous' }).click();
  await expect(page.getByText('Total Records:')).toBeVisible();
  await page.getByRole('link', { name: ' Employment' }).click();
});